### ISSUE TITLE
vue support

### ISSUE THREAD

**Issue by bypanghu** [pqoqubbw/icons#12]
Is the author willing to use it as a public lib library to support vue?

**Comment by pqoqubbw** [comment]
not right now. if anyone wants to adapt it for vue - go for it, i'm totally cool with that! but i'm not planning to expand the icons to other frameworks myself at the moment, i want to focus on adding as many new icons as possible

**Comment by imfenghuang** [comment]
hi @bypanghu , try it [imfenghuang/icons](https://github.com/imfenghuang/icons) 😊
