### ISSUE TITLE
How to trigger animation

### ISSUE THREAD

**Issue by edwinm** [pqoqubbw/icons#19]
Some documentation is still missing.

I can't find anywhere how an animation is triggered.

**Comment by pqoqubbw** [comment]
hey, it's using `framer-motion` for animation and `useAnimation` hook. you can check more info about it [here](https://www.framer.com/motion/use-animation-controls/)

**Comment by Vicentesan** [comment]
Is there anyway to trigger the animation the first time the component is rendered?
