### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by moshetanzer** [pqoqubbw/icons#22]
Hi,

Love the icons. Website is now down.

**Comment by pqoqubbw** [comment]
could you please provide a screenshot?

**Comment by moshetanzer** [comment]
![image](https://github.com/user-attachments/assets/c1fcf0ae-67ab-4623-84ea-9b1663272ecd)

**Comment by pqoqubbw** [comment]
what url were you trying to open? could you please send it here?

**Comment by netcrawlerr** [comment]
the site works fine

**Comment by waleedcodes** [comment]
Changing the browser may be a Cache issue!

**Comment by moshetanzer** [comment]
this is still down for me - tried diffrent browser etc...

**Comment by pqoqubbw** [comment]
@moshetanzer, i really don't know why. for 99.99% users website is working without any issue. maybe it's an issue on your side, cause from my side all things should be okay

i tried different browser to reproduce your state and still all working fine

**Comment by netcrawlerr** [comment]
I can also confirm, the site is working fine
