### ISSUE TITLE
How to remove the transition after change the icon

### ISSUE THREAD

**Issue by hong-tm** [pqoqubbw/icons#30]
sometimes that is empty for a while after i change to the sun icon

https://github.com/user-attachments/assets/f5cdea29-3d4c-4bee-a5c4-19af9620cfb4

**Comment by hong-tm** [comment]
it just blank for a while

**Comment by hong-tm** [comment]
fast click is ok

https://github.com/user-attachments/assets/4b01f894-f346-4d5e-b6fa-08ef6df531c3

**Comment by pqoqubbw** [comment]
it's not an icon problem, it's an implementation problem, try to look at the framer-motion documentation
