### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by imfenghuang** [pqoqubbw/icons#40]
hi @pqoqubbw, thanks to your project, and  i made a project to support Vue based on it.
Repo: [imfenghuang/icons](https://github.com/imfenghuang/icons) 
Demo: [https://imfenghuang.github.io/icons/](https://imfenghuang.github.io/icons/) 
It's not perfect yet, I will try my best to improve it.

**Comment by pqoqubbw** [comment]
you're crushing it! thank you so much for this awesome work ❤️
i'll add the link to your repo to the readme

**Comment by pqoqubbw** [comment]
done 350881458a0a4f20ca68567cd505e1c39a12051e
