### ISSUE TITLE
HOW ABOUT whole new ones WITHOUT framer

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [pqoqubbw/icons#65]
check out [this](https://courses.nan.fyi/blog/svg/animating-figma-exports#splitting-the-vector-in-figma), 
It has sections to really let you customize real beautiful, expose a really flexible API for it if you thinking of building a CLI or package or something
![image](https://github.com/user-attachments/assets/cab7758a-0f6d-43c7-8c13-53119024b787)

**Comment by imfenghuang** [comment]
cool!
I think the most of the icons can be implemented by CSS animation, but some can not that must need js to support. If we downgrade and simplify the animation, it should be possible.

**Comment by pqoqubbw** [comment]
thanks, that's a great article! i’m not planning to create animations with plain CSS at the moment - just don’t have enough time right now. but if someone else wants to work on it, i’d be happy to review and merge their changes!

**Comment by Ebrahim-Ramadan** [comment]
> thanks, that's a great article! i’m not planning to create animations with plain CSS at the moment - just don’t have enough time right now. but if someone else wants to work on it, i’d be happy to review and merge their changes!

sounds like @imfenghuang is the one for it

**Comment by olivebishop** [comment]
> thanks, that's a great article! i’m not planning to create animations with plain CSS at the moment - just don’t have enough time right now. but if someone else wants to work on it, i’d be happy to review and merge their changes!

i think there is animation for CSS in place check out - https://rombo.co/tailwind/

**Comment by olivebishop** [comment]
> cool! I think the most of the icons can be implemented by CSS animation, but some can not that must need js to support. If we downgrade and simplify the animation, it should be possible.

have a look at this - https://rombo.co/tailwind/

**Comment by pqoqubbw** [comment]
i guess i can close this issue
