### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by Vicentesan** [pqoqubbw/icons#7]
## Description: 
First of all, I want to say that I absolutely love the idea of this project! 😍 Providing free, open-source animated icons is fantastic and fills a much-needed space. However, I have a few suggestions for additional icons that could make the collection even more comprehensive and versatile.

### Communication Icons:

- Email 📧
- Phone call 📞
- Text message 💬

### Notification Status Icons:

- Multiple states of the bell icon 🔔 (muted, with notifications, without notifications)

### Navigation and Structure:

- Chevron arrows for navigation (left, right, up, down) ➡️⬅️⬆️⬇️
- Hamburger menu and vertical dots menu
-Back and forward arrows ⏮️⏭️

### Social Media Icons:

- LinkedIn
- Twitter
- GitHub
- Facebook
- Instagram
- Nostr
- ...

### Utility Icons:

- Trash 🗑️
- Settings ⚙️
- Help/Question mark ❓
- Save/Floppy disk 💾
- Favorite/Like ❤️⭐

I believe that these additional icons would be highly useful and cover even more use cases. I’d be happy to discuss more details if needed!

**Comment by pqoqubbw** [comment]
thanks for your feedback ❤️

i've already updated the structure and polished a few things. now i'm going to focus on adding new basic icons that everyone needs for their projects

**Comment by Vicentesan** [comment]
Hey, doing great?

Im looking foward to it... do you have some update in the progress?

**Comment by pqoqubbw** [comment]
hey, yep, most of the suggested icons are already added. i’ve kept this issue open so contributors can view the suggestions and add any icons they find useful

**Comment by 0xRaduan** [comment]
hey @pqoqubbw, I think I missed facebook icon somehow?
![image](https://github.com/user-attachments/assets/b3e31711-145a-4087-b3a3-580ed726afc6)

not seeing it in commits/on the website

**Comment by pqoqubbw** [comment]
i guess most of the icons have been added, so can close this issue
