### ISSUE TITLE
Missing Moon Icon

### ISSUE THREAD

**Issue by TheRedRacing** [pqoqubbw/icons#75]
First of all, I want to say I love your project! I'm currently working on adding dark and light mode functionality to my app. However, I noticed that the Moon icon, which is essential for toggling between the modes, is missing from the available icons.

Would it be possible to add a Moon icon to the library? It would be incredibly helpful for implementing a seamless user experience in my app.

Thank you for your amazing work and for considering this feature request! 😊

**Comment by pqoqubbw** [comment]
thank you for your words 🫶

moon icon added! d7c42e29edf7ae0e5f46fa6456ed09bfd17a55f3

**Comment by TheRedRacing** [comment]
No worries, if you want you can check on [Heroicons](https://heroicons.com/) website to find some icons you forgot. 👍🏼

**Comment by pqoqubbw** [comment]
> No worries, if you want you can check on [Heroicons](https://heroicons.com/) website to find some icons you forgot. 👍🏼

thanks!
