### ISSUE TITLE
Change shadcn cli command to use latest.

### ISSUE THREAD

**Issue by aumirza** [pqoqubbw/icons#79]
When i am using a command like

`npx shadcn add "https://icons.pqoqubbw.dev/c/moon.json`

it is prompting to install older version of shadcn 

but when i do 

`npx shadcn@latest add "https://icons.pqoqubbw.dev/c/connect.json`

It works fine.

**Comment by pqoqubbw** [comment]
fixed, thank you for pointing that out! ada82733f76ede52b5e6b5e9e7202ff59acae1f1
